program HRManager;

uses
  Forms,
  DM in 'DM.pas' {DataModule1: TDataModule},
  CITEZENUnit in 'CITEZENUnit.pas' {CITEZEN},
  ORGANISATIONUnit in 'ORGANISATIONUnit.pas' {ORGANISATION},
  GENERALDICTUnit in 'GENERALDICTUnit.pas' {GENERALDICT},
  DICTCONTENTEDITUnit in 'DICTCONTENTEDITUnit.pas' {DICTCONTENTEDIT},
  DOCEDUCATIONUnit in 'DOCEDUCATIONUnit.pas' {DOCEDUCATION},
  DOCEDUCATIONEDITUnit in 'DOCEDUCATIONEDITUnit.pas' {DOCEDUCATIONEDIT},
  GENERALDICTEDITUnit in 'GENERALDICTEDITUnit.pas' {GENERALDICTEDIT},
  DOCPASSPORTUnit in 'DOCPASSPORTUnit.pas' {DOCPASSPORT},
  LANGUAGEEDITUnit in 'LANGUAGEEDITUnit.pas' {LANGUAGEEDIT},
  MILITARYEDITUnit in 'MILITARYEDITUnit.pas' {MILITARYEDIT},
  OKSOUnit in 'OKSOUnit.pas' {OKSO},
  VACANCY_CONJUCTIONUnit in 'VACANCY_CONJUCTIONUnit.pas' {VACANCY_CONJUCTION},
  ORGANISATIONEDITUnit in 'ORGANISATIONEDITUnit.pas' {ORGANISATIONEDIT},
  DOCPASSPORTEDITUnit in 'DOCPASSPORTEDITUnit.pas' {DOCPASSPORTEDIT},
  EDUCATIONORGSUnit in 'EDUCATIONORGSUnit.pas' {EDUCATIONORGS},
  CITEZENEDITUnit in 'CITEZENEDITUnit.pas' {CITEZENEDIT},
  FAMILYCITEZENUnit in 'FAMILYCITEZENUnit.pas' {FAMILYCITEZEN},
  FAMILYCITEZENEDITUnit in 'FAMILYCITEZENEDITUnit.pas' {FAMILYCITEZENEDIT},
  FAMILYEDITUnit in 'FAMILYEDITUnit.pas' {FAMILYEDIT},
  JOBTITLEDITUnit in 'JOBTITLEDITUnit.pas' {EDITJOBTITLE},
  OKSOEDITUnitUnit in 'OKSOEDITUnitUnit.pas' {OKSOEDIT},
  HISTORYSCHEDUnit in 'HISTORYSCHEDUnit.pas' {HISTORYSCHED},
  OKPDTRUnit in 'OKPDTRUnit.pas' {OKPDTR},
  SALARYUnit in 'SALARYUnit.pas' {SALARY},
  ATESTATIONEDITUnit in 'ATESTATIONEDITUnit.pas' {ATESTATIONEDIT},
  CITEZENLISTUnit in 'CITEZENLISTUnit.pas' {CITEZENLIST},
  SKILLUPUnit in 'SKILLUPUnit.pas' {SKILLUPEDIT},
  RETRAININGEDITUnit in 'RETRAININGEDITUnit.pas' {RETRAININGEDIT},
  AWARDEDITUnit in 'AWARDEDITUnit.pas' {AWARDEDIT},
  HOLIDAYEDITUnit in 'HOLIDAYEDITUnit.pas' {HOLIDAYEDIT},
  SOCIALEDITUnit in 'SOCIALEDITUnit.pas' {SOCIALEDIT},
  SALARYEDITUnit in 'SALARYEDITUnit.pas' {SALARYEDIT},
  QUALIFICATIONUnit in 'QUALIFICATIONUnit.pas' {QUALIFICATION},
  PHONENUMBEREDITUnit in 'PHONENUMBEREDITUnit.pas' {PHONENUMBEREDIT},
  DISCIPLINEEDITUnit in 'DISCIPLINEEDITUnit.pas' {DISCIPLINEEDIT},
  INSURANCEUnit in 'INSURANCEUnit.pas' {INSURANCEEDIT},
  CONJUCTIONUnit in 'CONJUCTIONUnit.pas' {CONJUCTION},
  TOTALDATAUnit in 'TOTALDATAUnit.pas' {TOTALDATA},
  DISMISSUnit in 'DISMISSUnit.pas' {DISMISS},
  EMPLOYEEUnit in 'EMPLOYEEUnit.pas' {EMPLOYEE},
  EMPLOYEEDITUnit in 'EMPLOYEEDITUnit.pas' {EMPLOYEEDIT},
  VACANCYUnit in 'VACANCYUnit.pas' {VACANCY},
  DISMISSOREDERUnit in 'DISMISSOREDERUnit.pas' {DISMISSORDER},
  APPOINTMENTEDITUnit in 'APPOINTMENTEDITUnit.pas' {APPOINTMENTEDIT},
  ADDRESSEDIT in 'ADDRESSEDIT.pas' {ADDRESS},
  FIASCITYUnit in 'FIASCITYUnit.pas' {FIASCITY},
  REPORTUnit in 'REPORTUnit.pas' {WREPORT},
  EXTAGREEMENTUnit in 'EXTAGREEMENTUnit.pas' {EXTAGREEMENT},
  JOBTITLE_NPOUnit in 'JOBTITLE_NPOUnit.pas' {JOBTITLENPO},
  EDITJOBTITLENPOUnit in 'EDITJOBTITLENPOUnit.pas' {EDITJOBTITLENPO},
  ORDERUnit in 'ORDERUnit.pas' {ORDER},
  ORDEREDITUnit in 'ORDEREDITUnit.pas' {ORDEREDIT},
  EXTVACANCYUnit in 'EXTVACANCYUnit.pas' {EXTVACANCY},
  AREAUnit in 'AREAUnit.pas' {AREA},
  DOCREFERENCEUnit in 'DOCREFERENCEUnit.pas' {DOCREFERENCE},
  DOCAGREEMENTCONFUnit in 'DOCAGREEMENTCONFUnit.pas' {DOCAGREEMENTCONF},
  WORKCALENDARUnit in 'WORKCALENDARUnit.pas' {WORKCALENDAR},
  DOCWORKCONTRACTEDITUnit in 'DOCWORKCONTRACTEDITUnit.pas' {DOCWORKCONTRACTEDIT},
  JOBHISTORYUnit in 'JOBHISTORYUnit.pas' {JOBHISTORY},
  CONTWORKERUnit in 'CONTWORKERUnit.pas' {CONTWORKER},
  CONTWORKEREDITUnit in 'CONTWORKEREDITUnit.pas' {CONTWORKEREDIT},
  VACANCYEDITUnit in 'VACANCYEDITUnit.pas' {VACANCYEDIT},
  STORAGECONTRACTUnit in 'STORAGECONTRACTUnit.pas' {STORAGECONTRACT},
  MISSIONORDEREDITUnit in 'MISSIONORDEREDITUnit.pas' {MISSIONORDER},
  APPOINTMENTCHANGEUnit in 'APPOINTMENTCHANGEUnit.pas' {APPOINTMENTCHANGE},
  UNUSE_HOLIDAYSUnit in 'UNUSE_HOLIDAYSUnit.pas' {UNUSE_HOLIDAYS},
  JOBSCHEDULEUnit in 'JOBSCHEDULEUnit.pas' {JOBSCHEDULE},
  JOBHISTORYEDITUnit in 'JOBHISTORYEDITUnit.pas' {JOBHISTORYEDIT},
  PKDBQueryToExcel in 'PKDBQueryToExcel.pas',
  PROJEMPLOYEEDITUnit in 'PROJEMPLOYEEDITUnit.pas' {PROJEMPLOYEEDIT},
  MILITARYDEPTUnit in 'MILITARYDEPTUnit.pas' {MILITARYDEPT},
  SOCIALDEPTUnit in 'SOCIALDEPTUnit.pas' {SOCIALDEPT},
  ATTCOURSEEDITUnit in 'ATTCOURSEEDITUnit.pas' {ATTCOUSEEDIT},
  ATTCOURSEUnit in 'ATTCOURSEUnit.pas' {ATTCOUSE},
  PROFESSIONEDITUnit in 'PROFESSIONEDITUnit.pas' {PROFFESIONEDIT},
  PROFESSIONUnit in 'PROFESSIONUnit.pas' {PROFFESION},
  DOCLEAVEUnit in 'DOCLEAVEUnit.pas' {DOCLEAVEListForm},
  EditDialogUnit in '..\LIB\PKDBSoft\EditDialogUnit.pas' {EditDialog},
  DOCLEAVEEDITUnit in 'DOCLEAVEEDITUnit.pas' {DOCLEAVEEDIT},
  DMENUUnit in 'DMENUUnit.pas' {BMenuForm},
  REGIONUnit in 'REGIONUnit.pas' {REGION},
  ORGANISATION_MILITARYUnit in 'ORGANISATION_MILITARYUnit.pas' {ORGANISATION_MILITARY},
  DictUnit in '..\LIB\PKDBSoft\DictUnit.pas' {DictForm},
  ORGANISATION_PASSPORTUnit in 'ORGANISATION_PASSPORTUnit.pas' {ORGANISATION_PASSPORT};

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.Title := 'Кадровый учет';
  Application.CreateForm(TDataModule1, DataModule1);
  if DataModule1.PKDBLogin1.Execute = '-1' then exit;
  Application.CreateForm(TBMenuForm, BMenuForm);
  BMenuForm.Caption:=  'Кадровый учет';
  Application.Run;

  // устанавливаем кошерный формат NLS
  DM.DataModule1.alter_nls.Execute;
end.


